# Try container-based infrastucture
#sudo: false

notifications:
  email: false

language: python

matrix:
  include:
    - python: 3.7
      os: linux
      dist: bionic
      sudo: true
    - python: 3.8
      os: linux
      dist: bionic
      sudo: true
    
before_install:
  - ./.travis_before_install.sh

install:
  - ./.travis_install.sh
 
script:
  - ./.travis_test.sh

#after_success:
#  - ./.travis_deploy.sh
